spring.datasource.url=jdbc:postgresql://dpg-d8ie6q5dt1ts73f7u0tg-a.oregon-postgres.render.com/shaoume_db
spring.datasource.username=shaoume_db_user
spring.datasource.password=rJNOa8hLxmfiCYzZqPrL2bRNX4lAFyI3
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
